### ISSUE TITLE
Doc suggestion: verifyAuthenticityToken cannot be used with request if the request body has been accessed

### ISSUE THREAD

**Issue by dawnmist** [kentcdodds/epic-stack-with-csrf#2]
I've just used this example to add csrf to the site I was working on, and tripped over an issue that the `verifyAuthenticityToken` function needs to be given the response before the body of it has been accessed.

e.g. this doesn't work (it throws due to the request body "having been used"):
```ts
	let session = await getSession(request.headers.get('Cookie'))
	const formData = await request.formData()
	await verifyAuthenticityToken(request, session)
```

This does work:
```ts
	let session = await getSession(request.headers.get('Cookie'))
	await verifyAuthenticityToken(request, session)
	const formData = await request.formData()
```

This also works
```ts
	let session = await getSession(request.headers.get('Cookie'))
	const formData = await request.formData()
	await verifyAuthenticityToken(formData, session)
```

Since I'd been wanting to wrap the verify in a try/catch and send back the contents of the form data in the catch clause's error, I'd defaulted to using the first way only to be very confused when the catch clause was firing (the error object seemed to be empty as a result of misconfiguring winston, so I wasn't getting any useful information from it). It's an unexpected limitation that is really easy to trip over.

(Thank you so much for your work and examples on the Epic Stack!)

**Comment by kentcdodds** [comment]
Good point! I've updated the example 👍 Part of me feels like accepting the request should be disallowed by the library for this reason.
